class CreateWitsRecords < ActiveRecord::Migration
  def change
    create_table :wits_records do |t|
      t.integer :company_id
      t.integer :job_id

      t.datetime :entry_at

      t.float :bit_depth
      t.float :hole_depth
      t.float :min_convertible_torque
      t.float :hook_load
      t.float :standpipe_pressure
      t.float :rotary_rpm
      t.float :rotary_torque
      t.float :weight_on_bit
      t.float :on_bottom_rop
      t.float :flow
      t.float :total_mud_volume
      t.float :trip_tank_mud_volume
      t.float :line_wear
      t.float :casing_pressure
      t.float :pump1_rate
      t.float :pump2_rate
      t.float :pump3_rate
      t.float :pump4_rate
      t.float :pump1_total_strokes
      t.float :pump2_total_strokes
      t.float :pump3_total_strokes
      t.float :pump4_total_strokes
      t.float :total_strokes
      t.float :total_pump_output
      t.float :total_pump_displacement
      t.float :block_height
      t.float :mud_tank1_volume
      t.float :mud_tank2_volume
      t.float :mud_tank3_volume
      t.float :mud_tank4_volume
      t.float :mud_tank5_volume
      t.float :on_bottom_hours
      t.float :circulating_hours
      t.float :explosive_gas1
      t.float :explosive_gas2
      t.float :tool_face
      t.float :inclination
      t.float :azimuth
      t.float :gamma
      t.float :mud_gl_alarm_state
      t.float :flow_1_gl_alarm_state
      t.float :magnetic_tool_face
      t.float :gravity_tool_face
      t.float :mwd_vibration_xyz
      t.float :mwd_temperature
      t.float :mwd_general_variable1
      t.float :mwd_general_variable2
      t.float :mwd_general_variable3
      t.float :mwd_general_variable4
      t.float :mwd_vibration_xyz_gamma
      t.float :mwd_vibration_xy_gamma
      t.float :mwd_vibration_z_gamma
      t.float :over_pull
      t.float :fill_strokes
      t.float :total_fill_strokes
      t.float :min_pressure
      t.float :min_hook_load
      t.float :min_torque
      t.float :min_rpm
      t.float :min_wob
      t.float :relative_mse
      t.float :cement_fluid_temp
      t.float :mwd_vibration_count
      t.float :sensor_depth
      t.float :pvt_total_mud_gain_loss
      t.float :differential_pressure
      t.float :pason_lag_depth
      t.float :tts_weight_on_bit
      t.float :drilling_activity
      t.float :min_tts_weight_on_bit
      t.float :choke_position
      t.float :trip_speed
      t.float :gamma_depth
      t.float :gamma_at_bit
      t.float :resistivity2
      t.float :formation_density
      t.float :res2_at_bit
      t.float :fdens_at_bit
      t.float :percent_wits_gas
      t.float :motor_rpm
      t.float :convertible_torque
      t.float :p1_rate
      t.float :p2_rate
      t.float :pvt_mud_tanks_included
      t.float :pvt_monitor_mud_gl
      t.float :pvt_mud_gl_threshold
      t.float :trip_tank_1_refill_status
      t.float :trip_tank_1_low_threshold
      t.float :trip_tank_1_high_threshold
      t.float :flow_1_gl
      t.float :flow_1_gl_threshold
      t.float :xy_accel_severity_level
      t.float :z_accel_severity_level
      t.float :trip_tank_fill
      t.float :trip_tank_accum
      t.float :rate_of_penetration
      t.float :time_of_penetration
      t.float :autodriller_status
      t.float :autodriller_sensitivity
      t.float :autodriller_drum_ticks
      t.float :autodriller_wob
      t.float :autodriller_wob_sp
      t.float :autodriller_brake_pos
      t.float :autodriller_diff_press
      t.float :autodriller_diff_press_sp
      t.float :autodriller_torque
      t.float :autodriller_torque_limit
      t.float :autodriller_status_uw
      t.float :autodriller_status_lw
      t.float :autodriller_status_2_uw
      t.float :autodriller_status_2_lw
      t.float :autodriller_timedrill_sp
      t.float :autodriller_rop_sp
      t.float :autodriller_ticks_per_depth


      t.timestamps
    end
  end
end
